### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by tehila17-meet** [jacklishufan/InstructAny2Pix#2]
Can you check why?

**Comment by jacklishufan** [comment]
Hi. Do you mean the demo link or the code. If it's about the demo link, we are hosting the demo ourself and currently we are using that machine to run some additional experiments. You should see the link back on line after Jan 31st. Sorry for the inconvenience. If its about the code and you are running it yourself, please provide more details about error/exception, thanks!

**Comment by tehila17-meet** [comment]
hey, yeah i meant the demo link, i tried again today but its still getting an error (see attached image) 
<img width="990" alt="Screen Shot 2024-02-03 at 9 37 44" src="https://github.com/jacklishufan/InstructAny2Pix/assets/16003330/84d6387f-2370-482a-97d0-b92e9c77408c">

**Comment by jacklishufan** [comment]
Hi sorry for the inconvenience. It is now back online. Can you try it again?

**Comment by tehila17-meet** [comment]
amazing. Thank you it works :)
