### ISSUE TITLE
dependency version issues

### ISSUE THREAD

**Issue by tehila17-meet** [jacklishufan/InstructAny2Pix#4]
Hey, can you update the requirements with the new versions of each dependency? it seems like some are outdated, 
im getting an error in the diffusers: UNet2DConditionModel has no attirbute attn_processors

**Comment by jacklishufan** [comment]
Hi, I have updated the requirements to 0.24.0. It should work now. We also tested it against a later version (0.26.3),

**Comment by tehila17-meet** [comment]
Thnx! do you know what version of IP-Adpater you are using in production (which commit of theirs?)

**Comment by jacklishufan** [comment]
Hi, I think we use the version of  IP-Adpater that is integrated into diffusers and we did not use their repo explicitly

**Comment by tehila17-meet** [comment]
it seems like there is still some mismatch with the dependencies. I keep on getting this error (when i try running the model through gradio): 
Have you had this error? 

File "/home/ubuntu/.conda/envs/instructany2pix/lib/python3.10/site-packages/diffusers/loaders/ip_adapter.py", line 155, in set_ip_adapter_scale
    for attn_processor in self.unet.attn_processors.values():
  File "/home/ubuntu/.conda/envs/instructany2pix/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 222, in __getattr__
    return super().__getattr__(name)
  File "/home/ubuntu/.conda/envs/instructany2pix/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'UNet2DConditionModel' object has no attribute 'attn_processors'. Did you mean: 'set_attn_processor'?

**Comment by jacklishufan** [comment]
> it seems like there is still some mismatch with the dependencies. I keep on getting this error (when i try running the model through gradio): Have you had this error?
> 
> File "/home/ubuntu/.conda/envs/instructany2pix/lib/python3.10/site-packages/diffusers/loaders/ip_adapter.py", line 155, in set_ip_adapter_scale for attn_processor in self.unet.attn_processors.values(): File "/home/ubuntu/.conda/envs/instructany2pix/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 222, in **getattr** return super().**getattr**(name) File "/home/ubuntu/.conda/envs/instructany2pix/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1688, in **getattr** raise AttributeError(f"'{type(self).**name**}' object has no attribute '{name}'") AttributeError: 'UNet2DConditionModel' object has no attribute 'attn_processors'. Did you mean: 'set_attn_processor'?

Hi, can you try the following snippet:
```
import diffusers
print(diffusers.__version__)
from diffusers import UNet2DConditionModel

model = UNet2DConditionModel.from_pretrained('stabilityai/stable-diffusion-xl-base-1.0', subfolder="unet")
print(model.attn_processors)
```
On my side (0.24.0) this has no issue

**Comment by tehila17-meet** [comment]
Yeah so this snippet works, but it still gets this error in runtime, what is your torch version?

**Comment by jacklishufan** [comment]
New requirements have been updated
