### ISSUE TITLE
AttributeError: 'InstructAny2PixLMModel' object has no attribute '_prepare_decoder_attention_mask'

### ISSUE THREAD

**Issue by kojunseok0217** [jacklishufan/InstructAny2Pix#8]
Hello. Thank you for amazing projects.
I run the Demo-Retrained.ipynb and encounter error message "AttributeError: 'InstructAny2PixLMModel' object has no attribute '_prepare_decoder_attention_mask'".
It seems like the error "AttributeError: 'InstructAny2PixLMModel' object has no attribute '_prepare_decoder_attention_mask'" is occurring due to a mismatch in package versions. Could you please provide the exact versions of the packages that need to be installed to resolve this issue?
![image](https://github.com/jacklishufan/InstructAny2Pix/assets/109671206/8a5374fd-ed8a-4171-aa09-83ef9a4de804)
Thanks.

**Comment by jacklishufan** [comment]
See https://github.com/jacklishufan/InstructAny2Pix/issues/7#issuecomment-2212329582
